### ISSUE TITLE
Caught a C++ exception when unpack files which in japanese

### ISSUE THREAD

**Issue by liaoyinuo** [nextgal/pfs_upk#8]
![image](https://github.com/nextgal/pfs_upk/assets/55882882/84fddd2a-6a10-45c0-9a5c-bc787fb6d8a6)

![image](https://github.com/nextgal/pfs_upk/assets/55882882/ad8dd294-b89d-402d-a4a8-c44499e2602c)

It seems to be problem with encoding. It works well when i unpack the file in pure english.

**Comment by liaoyinuo** [comment]
There comes a same promblem today. I try to move the .001 to a isoloate foloder and it works. It seems that when .000 .001 .002 etc. subsection in a same floder will cause this problem.

**Comment by ryank231231** [comment]
> There comes a same promblem today. I try to move the .001 to a isoloate foloder and it works. It seems that when .000 .001 .002 etc. subsection in a same floder will cause this problem.

about the problem unpacking example.pfs.00x , see #6 

and i'll fix the decoding issue in the near future, because i'm so busy recently ;-(

**Comment by ryank231231** [comment]
fixed in v1.2.0 release.

**Comment by suphamster** [comment]
Still not fixed for me, tested on https://github.com/nextgal/pfs_upk/commit/abdffcbeb3c733ce234aa99ed42b206d13aaed2f this commit (can't build in VS22 earlier commits due 2 errors), I have TheShell2.pfs, TheShell2.pfs.000, TheShell2.pfs.001 and etc files, 1st one unpacks fine but others only after renaming to TheShell2.pfs.
